### ISSUE TITLE
wrong tomcat user and group in conf instance directory

### ISSUE THREAD

**Issue by matteoturra** [example42/puppet-tomcat#26]
Creating an instance passing owner and group the resulting conf directory inherit owner and group from system default.
I think a chown -R ${OWNER}:${GROUP} ${TARGET}/conf is missing at the end of configuration changes.

Patch:
diff --git a/templates/instance/tomcat-instance-create.erb b/templates/instance/tomcat-instance-create.erb
index 5bd9901..460b921 100644
--- a/templates/instance/tomcat-instance-create.erb
+++ b/templates/instance/tomcat-instance-create.erb
@@ -165,6 +165,7 @@ sed -i -e "s/Connector port=\"8080\"/Connector port=\"${HPORT}\"/;s/Server port=
 <% end -%>
 
 sed -i -e "s/Connector port=\"8009\"/Connector port=\"${APORT}\"/g" ${TARGET}/conf/server.xml
+chown -R ${OWNER}:${GROUP} ${TARGET}/conf
 
 cat > ${TARGET}/bin/startup.sh << EOT
 #!/bin/sh

**Comment by alvagante** [comment]
applied the patch, thx
